# Travis-CI Build for OpenRAModSDK
# see travis-ci.org for details

language: csharp
mono: 4.6.1
sudo: false

addons:
  apt:
    packages:
    - liblua5.1-0
    - nsis
    - nsis-common

script:
 - make
 - . mod.config;
   awk '/\r$$/ { exit(1); }' mod.config || (printf "Invalid mod.config format. File must be saved using unix-style (CR, not CRLF) line endings.\n"; travis_terminate 1);
   if [ "${TRAVIS_TEST_MOD}" == "True" ]; then make test || travis_terminate 1; fi;
   if [ "${TRAVIS_TEST_PACKAGING}" == "True" ]; then make check-packaging-scripts && ./packaging/package-all.sh test-0 || travis_terminate 1; fi

before_deploy:
 - mkdir build
 - make check-packaging-scripts && cd build && ../packaging/package-all.sh ${TRAVIS_TAG} ${PWD} && cd ..
 - . mod.config

deploy:
  provider: releases
  api_key: ${GH_DEPLOY_API_KEY}
  file:
    - build/${PACKAGING_INSTALLER_NAME}-${TRAVIS_TAG}.exe
    - build/${PACKAGING_INSTALLER_NAME}-${TRAVIS_TAG}-macOS.zip
    - build/${PACKAGING_INSTALLER_NAME}-${TRAVIS_TAG}-winportable.zip
    - build/${PACKAGING_INSTALLER_NAME}-${TRAVIS_TAG}.AppImage
  skip_cleanup: true
  on:
    tags: true
